In [8]:
import requests 
from bs4 import BeautifulSoup
import csv
import json

base_url = "https://books.toscrape.com/catalogue/"

books_data = []

for i in range(1, 51):
    current_url = f"{base_url}page-{i}.html"
    response = requests.get(current_url)
    soup = BeautifulSoup(response.text, 'html.parser')
    books = soup.find_all('article', class_='product_pod')
    for book in books:
            title = book.h3.a['title']
            price = float(book.find('p', class_='price_color').text[2:]) 
            availability = book.find('p', class_='instock availability').text.strip()

            data = {
                'title': title,
                'price': price,
                'availability': availability
            }
            books_data.append(data)

# Save data to CSV
with open('books_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
    fieldnames = ['title', 'price', 'availability']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for book in books_data:
        writer.writerow(book)

# Save data to JSON
with open('books_data.json', 'w') as jsonfile:
    json.dump(books_data, jsonfile, indent=4)

In [9]:
print(books_data[0])

{'title': 'A Light in the Attic', 'price': 51.77, 'availability': 'In stock'}

In [11]:
import pandas as pd

# Load data from CSV
books_df = pd.read_csv('books_data.csv')

books_df[books_df['price'] > 50]

                                                 title  price availability
0                                 A Light in the Attic  51.77     In stock
1                                   Tipping the Velvet  53.74     In stock
2                                           Soumission  50.10     In stock
4                Sapiens: A Brief History of Humankind  54.23     In stock
9                                      The Black Maria  52.15     In stock
..                                                 ...    ...          ...
978               Giant Days, Vol. 1 (Giant Days #1-4)  56.76     In stock
984                                    Eat, Pray, Love  51.32     In stock
995  Alice in Wonderland (Alice's Adventures in Won...  55.53     In stock
996   Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)  57.06     In stock
998                1st to Die (Women's Murder Club #1)  53.98     In stock

[198 rows x 3 columns]

In [12]:
books_df[books_df['price'] < 20]

                                                 title  price availability
7    The Coming Woman: A Novel Based on the Life of...  17.93     In stock
10      Starving Hearts (Triangular Trade Trilogy, #1)  13.99     In stock
12                                         Set Me Free  17.46     In stock
20                                         In Her Wake  12.84     In stock
30   The Four Agreements: A Practical Guide to Pers...  17.66     In stock
..                                                 ...    ...          ...
938                      The Complete Maus (Maus #1-2)  10.64     In stock
939                            The Communist Manifesto  14.76     In stock
943                        Taking Shots (Assassins #1)  18.88     In stock
946                    Sister Sable (The Mad Queen #1)  13.33     In stock
997  A Spy's Devotion (The Regency Spies of London #1)  16.97     In stock

[196 rows x 3 columns]

In [24]:
books_df[books_df['availability'].str.contains('In stock')].count()

title           1000
price           1000
availability    1000
dtype: int64