In [1]:
import requests 
from bs4 import BeautifulSoup
import csv
import json

base_url = "https://books.toscrape.com/catalogue/"

books_data = []

for i in range(1, 51):
    current_url = f"{base_url}page-{i}.html"
    response = requests.get(current_url)
    soup = BeautifulSoup(response.text, 'html.parser')
    books = soup.find_all('article', class_='product_pod')
    for book in books:
            title = book.h3.a['title']
            price = float(book.find('p', class_='price_color').text[2:]) 
            availability = book.find('p', class_='instock availability').text.strip()

            data = {
                'title': title,
                'price': price,
                'availability': availability
            }
            books_data.append(data)

# Save data to CSV
with open('books_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
    fieldnames = ['title', 'price', 'availability']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for book in books_data:
        writer.writerow(book)

# Save data to JSON
with open('books_data.json', 'w') as jsonfile:
    json.dump(books_data, jsonfile, indent=4)

In [2]:
print(books_data[0])

{'title': 'A Light in the Attic', 'price': 51.77, 'availability': 'In stock'}

In [3]:
import pandas as pd

# Load data from CSV
books_df = pd.read_csv('books_data.csv')

books_df[books_df['price'] > 50]

                                                 title  price availability
0                                 A Light in the Attic  51.77     In stock
1                                   Tipping the Velvet  53.74     In stock
2                                           Soumission  50.10     In stock
4                Sapiens: A Brief History of Humankind  54.23     In stock
9                                      The Black Maria  52.15     In stock
..                                                 ...    ...          ...
978               Giant Days, Vol. 1 (Giant Days #1-4)  56.76     In stock
984                                    Eat, Pray, Love  51.32     In stock
995  Alice in Wonderland (Alice's Adventures in Won...  55.53     In stock
996   Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)  57.06     In stock
998                1st to Die (Women's Murder Club #1)  53.98     In stock

[198 rows x 3 columns]

In [4]:
books_df[books_df['price'] < 20]

                                                 title  price availability
7    The Coming Woman: A Novel Based on the Life of...  17.93     In stock
10      Starving Hearts (Triangular Trade Trilogy, #1)  13.99     In stock
12                                         Set Me Free  17.46     In stock
20                                         In Her Wake  12.84     In stock
30   The Four Agreements: A Practical Guide to Pers...  17.66     In stock
..                                                 ...    ...          ...
938                      The Complete Maus (Maus #1-2)  10.64     In stock
939                            The Communist Manifesto  14.76     In stock
943                        Taking Shots (Assassins #1)  18.88     In stock
946                    Sister Sable (The Mad Queen #1)  13.33     In stock
997  A Spy's Devotion (The Regency Spies of London #1)  16.97     In stock

[196 rows x 3 columns]

In [5]:
books_df[books_df['availability'].str.contains('In stock')].count()

title           1000
price           1000
availability    1000
dtype: int64

In [22]:
books_df.sort_values(by='title', key=lambda x: x.str.lower()).head(20)

                                                 title  price availability
491  "Most Blessed of the Patriarchs": Thomas Jeffe...  44.48     In stock
887                                          #GIRLBOSS  50.96     In stock
43   #HigherSelfie: Wake Up Your Life. Free Your So...  23.11     In stock
691                                       'Salem's Lot  49.56     In stock
127  (Un)Qualified: How God Uses Broken People to D...  54.00     In stock
999                 1,000 Places to See Before You Die  26.08     In stock
418  10% Happier: How I Tamed the Voice in My Head,...  24.57     In stock
419  10-Day Green Smoothie Cleanse: Lose Up to 15 P...  49.71     In stock
417                                           11/22/63  48.48     In stock
355  13 Hours: The Inside Account of What Really Ha...  27.06     In stock
350  1491: New Revelations of the Americas Before C...  21.80     In stock
998                1st to Die (Women's Murder Club #1)  53.98     In stock
444  23 Degrees South: A Tropical Tale of Changing ...  35.79     In stock
490                                           32 Yolks  53.63     In stock
886           8 Keys to Mental Health Through Exercise  31.04     In stock
349               A Brush of Wings (Angels Walking #3)  55.51     In stock
644       A Clash of Kings (A Song of Ice and Fire #2)  10.79     In stock
126  A Court of Thorns and Roses (A Court of Thorns...  52.37     In stock
348      A Distant Mirror: The Calamitous 14th Century  14.58     In stock
643      A Feast for Crows (A Song of Ice and Fire #4)  17.21     In stock

In [7]:
books_df.sort_values(by='price', ascending=True)

                                                 title  price availability
638                         An Abundance of Katherines  10.00     In stock
501                              The Origin of Species  10.01     In stock
716  The Tipping Point: How Little Things Can Make ...  10.02     In stock
84                                            Patience  10.16     In stock
302                               Greek Mythic History  10.23     In stock
..                                                 ...    ...          ...
366                          The Diary of a Young Girl  59.90     In stock
560                     The Barefoot Contessa Cookbook  59.92     In stock
860                   Civilization and Its Discontents  59.95     In stock
617                  Last One Home (New Beginnings #1)  59.98     In stock
648                 The Perfect Play (Play by Play #1)  59.99     In stock

[1000 rows x 3 columns]